version: 2.1
jobs:
  build:
    docker:
      - image: typelead/eta:latest
    steps:
    - checkout

    - restore_cache:
        key: etlas-v1200-cache-

    - run: etlas update

    - run: etlas install

    - save_cache:
        key: etlas-v1200-cache-{{ epoch }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          # - "~/.etlas/patches"
          - "~/.etlas/tools"
          
workflows:
  version: 2
  full_cycle:
    jobs:
      - build
